name: Build APK

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Version Check
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Build APK
        run: flutter build apk --debug   # TEMP change

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-debug.apk